### PR TITLE
Add support for title and web_url in Inboard parameters 

### PR DESCRIPTION
**Pull request by fanzeyi**

### CODE REVIEW

**Comment by xhacker** [comment]
https://github.com/xhacker/Add-to-Inboard/commit/e36dc11ecfaa86e408012571868fb9e996b2526a 😂

**Comment by fanzeyi** [comment]
@xhacker 😂

**Comment by fanzeyi** [comment]
Dribbble is now using an overlay to present shot when you open it from a list such as opening a shot from the homepage. My second commit added the support in such situation. =)

**Comment by RayPS** [comment]
Works like a charm. Thank you :+1:

**Pull request merged**
